Front\MenuBundle\Entity\Menu:
  type: entity
  table: menu
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255
      unique: true
    name_ru:
      type: string
      length: 255
      unique: true
      nullable: true
    name_en:
      type: string
      length: 255
      nullable: true
    icon:
      type: string
      length: 255
      nullable: true
    url:
      type: string
      length: 255
      unique: true
      nullable: true
    is_activated:
      type: boolean
      nullable: true
    title:
      type: string
      length: 255
      nullable: true
    description:
      type: string
      length: 255
      nullable: true
    keywords:
      type: string
      length: 255
      nullable: true
    title_ru:
      type: string
      length: 255
      nullable: true
    description_ru:
      type: string
      length: 255
      nullable: true
    keywords_ru:
      type: string
      length: 255
      nullable: true
    title_en:
      type: string
      length: 255
      nullable: true
    description_en:
      type: string
      length: 255
      nullable: true
    keywords_en:
      type: string
      length: 255
      nullable: true
  oneToMany:
    listit:
      targetEntity: Listit
      mappedBy: menu
  manyToOne:
    menu:
      targetEntity: Menu
      inversedBy: menu
      joinColumn:
        name: menu_id
        referencedColumnName: id