admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

front_menu:
    resource: "@FrontMenuBundle/Resources/config/routing.yml"
    prefix:   /

front_top:
    resource: "@FrontTopBundle/Resources/config/routing.yml"
    prefix:   /
