Front_proj_index:
    path:     /
    defaults: { _controller: "FrontTopBundle:Activities:index" }
    methods:  GET

Front_proj_show:
    path:     /{id}/show
    defaults: { _controller: "FrontTopBundle:Activities:show" }
    methods:  GET

Front_proj_new:
    path:     /new
    defaults: { _controller: "FrontTopBundle:Activities:new" }
    methods:  [GET, POST]

Front_proj_edit:
    path:     /{id}/edit
    defaults: { _controller: "FrontTopBundle:Activities:edit" }
    methods:  [GET, POST]

Front_proj_delete:
    path:     /{id}/delete
    defaults: { _controller: "FrontTopBundle:Activities:delete" }
    methods:  DELETE
