Front_proj_i:
    path:     /
    defaults: { _controller: "FrontTopBundle:Activities:index",  page: 1}

Front_proj_index:
    path:     /{_locale}/
    defaults: { _controller: "FrontTopBundle:Activities:index",  page: 1}
    requirements:
      _locale:  en|ua|ru

Front_proj_show:
    path:     /activities/{url}/{_locale}
    defaults: { _controller: "FrontTopBundle:Activities:show" }
    methods:  GET
    requirements:
      _locale:  en|ua|ru

Front_proj2_show:
    path:     /project/{id}/{_locale}
    defaults: { _controller: "FrontTopBundle:Activities:showp" }
    methods:  GET
    requirements:
      _locale:  en|ua|ru