feedback_index:
    path:     /
    defaults: { _controller: "FrontTopBundle:Feedback:index" }
    methods:  GET

feedback_show:
    path:     /{id}/show
    defaults: { _controller: "FrontTopBundle:Feedback:show" }
    methods:  GET

feedback_new:
    path:     /new
    defaults: { _controller: "FrontTopBundle:Feedback:new" }
    methods:  [GET, POST]

feedback_edit:
    path:     /{id}/edit
    defaults: { _controller: "FrontTopBundle:Feedback:edit" }
    methods:  [GET, POST]

feedback_delete:
    path:     /{id}/delete
    defaults: { _controller: "FrontTopBundle:Feedback:delete" }
    methods:  DELETE
