AdminBundle\Entity\Admin:
  type: entity
  table: admin
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255
      unique: true
    permission:
      type: string
      length: 2555
      nullable: true
    email:
      type: string
      length: 255
      nullable: true
    password:
      type: boolean
      nullable: true
    created_at:
      type: datetime