Front\TopBundle\Entity\Feedback:
  type: entity
  table: feedback
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255
    email:
      type: string
      length: 255
    phone:
      type: string
      length: 255
    message:
      type: string
      length: 2555