Front\TopBundle\Entity\Mailsender:
  type: entity
  table: mailsender
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    email:
      type: string
      length: 255
    send_mail:
      type: boolean
