front_top_Front_proj:
    resource: "@FrontTopBundle/Resources/config/routing/activities.yml"
    prefix:   /
front_top_Front_foto:
    resource: "@FrontTopBundle/Resources/config/routing/foto.yml"
    prefix:   /Front_foto
