front_top_Front_proj:
    resource: "@FrontTopBundle/Resources/config/routing/activities.yml"
    prefix:   /
front_top_Front_feedback:
    resource: "@FrontTopBundle/Resources/config/routing/feedback.yml"
    prefix:   /feedback


