front_top_Front_proj:
    resource: "@FrontTopBundle/Resources/config/routing/activities.yml"
    prefix:   /Front_proj

front_top_homepage:
    path:     /
    defaults: { _controller: FrontTopBundle:Default:index }
