l_index:
    path:     /l
    defaults: { _controller: "FrontMenuBundle:Listit:index" }
    methods:  GET

l_show:
    path:     /{url}
    defaults: { _controller: "FrontMenuBundle:Listit:show" }
    methods:  GET

l_new:
    path:     /l/new
    defaults: { _controller: "FrontMenuBundle:Listit:new" }
    methods:  [GET, POST]

l_edit:
    path:     /l/{id}/edit
    defaults: { _controller: "FrontMenuBundle:Listit:edit" }
    methods:  [GET, POST]

l_delete:
    path:     /l/{id}/delete
    defaults: { _controller: "FrontMenuBundle:Listit:delete" }
    methods:  DELETE
