l_index:
    path:     /
    defaults: { _controller: "FrontMenuBundle:Listit:index" }
    methods:  GET

l_show:
    path:     /{id}/show
    defaults: { _controller: "FrontMenuBundle:Listit:show" }
    methods:  GET

l_new:
    path:     /new
    defaults: { _controller: "FrontMenuBundle:Listit:new" }
    methods:  [GET, POST]

l_edit:
    path:     /{id}/edit
    defaults: { _controller: "FrontMenuBundle:Listit:edit" }
    methods:  [GET, POST]

l_delete:
    path:     /{id}/delete
    defaults: { _controller: "FrontMenuBundle:Listit:delete" }
    methods:  DELETE
