m_index:
    path:     /
    defaults: { _controller: "FrontMenuBundle:Menu:index" }
    methods:  GET

m_show:
    path:     /{id}/show
    defaults: { _controller: "FrontMenuBundle:Menu:show" }
    methods:  GET

m_new:
    path:     /new
    defaults: { _controller: "FrontMenuBundle:Menu:new" }
    methods:  [GET, POST]

m_edit:
    path:     /{id}/edit
    defaults: { _controller: "FrontMenuBundle:Menu:edit" }
    methods:  [GET, POST]

m_delete:
    path:     /{id}/delete
    defaults: { _controller: "FrontMenuBundle:Menu:delete" }
    methods:  DELETE
